name: AutoInv
author: JackNoordhuis
description: Limits the amount of item entities in your server by adding item drops straight to entities inventories
version: 0.0.3
main: jacknoordhuis\autoinv\Main
api:
    - 1.0.0
    - 2.0.0